USE [master]
GO

/****** Object:  Database [Atiran2]    Script Date: 9/6/2026 9:32:08 PM ******/
CREATE DATABASE [Atiran2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sac_Data', FILENAME = N'D:\Database\Atiran2.mdf' , SIZE = 70080KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'sac_Log', FILENAME = N'D:\Database\Atiran2_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Atiran2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Atiran2].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Atiran2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Atiran2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Atiran2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Atiran2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Atiran2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Atiran2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Atiran2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Atiran2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Atiran2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Atiran2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Atiran2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Atiran2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Atiran2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Atiran2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Atiran2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Atiran2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Atiran2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Atiran2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Atiran2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Atiran2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Atiran2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Atiran2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Atiran2] SET RECOVERY FULL 
GO

ALTER DATABASE [Atiran2] SET  MULTI_USER 
GO

ALTER DATABASE [Atiran2] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Atiran2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Atiran2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Atiran2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Atiran2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Atiran2] SET  READ_WRITE 
GO

